<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */

defined('BASEPATH') or exit('No direct script access allowed');
require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");

class champions extends REST_Controller
{
    private $code01 = '001'; //CODIGO CORRECTO.
    private $code02 = '002'; //VALOR NO ENCONTRADO.
    private $code03 = '003'; //FALTAN PARAMETROS.
    private $code04 = '004'; //CODIGO NO CORRECTO.

    public function __construct()
    {
        parent::__construct();
        $this->load->model('Champions_model');
    }

    public function get_all_get()
    {

        $total_rows = $this->Champions_model->get_all_champions_count();

        $per_page = 10;

        $uri_segment = 5;

        $page = ($this->uri->segment(5)) ? $this->uri->segment(5) : 0;

        //$query = $this->Champions_model->get_all_champions();

        $champions = $this->Champions_model->get_all_champions(array('limit' => $per_page, 'offset' => $page));

        if (count($champions) > 0) {

            $data = array();

            foreach ($champions as $champion) {
                array_push($data, array(
                    'id' => $champion['id'],
                    'name' => $champion['name'],
                    'champ_key' => $champion['champ_key'],
                    'title' => $champion['title'],
                    'description' => $champion['description'],
                ));
            }

            $siguiente_pagina = 0;

            if ($this->uri->segment(5) == null) {
                $siguiente_pagina = $per_page;

                $this->response([
                    'status' => true,
                    'uri_segment' => $this->uri->segment(5),
                    'error' => false,
                    'message' => "OK",
                    'system_code' => $this->code01,
                    'data' => $data,
                    'next_page' => 'http://localhost/championsApi/api/v1/champions/get_all/' . $siguiente_pagina,
                ], 200);
            } else {
                $siguiente_pagina = $this->uri->segment(5) + $per_page;

                $antes_pagina = $this->uri->segment(5) - $per_page;

                $ultimaPagina = $antes_pagina < 0 ? 0 : $antes_pagina;

                $this->response([
                    'status' => true,
                    'uri_segment' => $this->uri->segment(5),
                    'last_page' => 'http://localhost/championsApi/api/v1/champions/get_all/' . $ultimaPagina,
                    'error' => false,
                    'message' => "OK",
                    'system_code' => $this->code01,
                    'data' => $data,
                    'next_page' => 'http://localhost/championsApi/api/v1/champions/get_all/' . $siguiente_pagina,
                ], 200);
            }

        } else {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR',
                'system_code' => $this->code02,
            ], 200);
        }
    }

    public function get_get()
    {
        $id_champion = trim($this->get('id', true));

        $champion = $this->Champions_model->get_champion($id_champion);

        if ($champion != null) {
            $this->response([
                'status' => true,
                'error' => false,
                'message' => "OK",
                'system_code' => $this->code01,
                'data' => $champion,
            ], 200);
        } else {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR',
                'system_code' => $this->code03,
            ], 200);
        }
    }

    public function add_post()
    {
        $name = $this->post('name');
        $champ_key = $this->post('champ_key');
        $title = $this->post('title');
        $description = $this->post('description');

        if ($name == '' || $champ_key == '' || $title == '' || $description == '') {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR',
                'system_code' => $this->code03,
            ], 400);
        } else {
            $champion = array(
                'name' => $name,
                'champ_key' => $champ_key,
                'title' => $title,
                'description' => $description,
            );

            $id_champion = $this->Champions_model->add_champion($champion);

            $champion = $this->Champions_model->get_champion($id_champion);

            if ($champion != null) {
                $this->response([
                    'status' => true,
                    'error' => false,
                    'message' => "OK",
                    'system_code' => $this->code01,
                    'data' => $champion,
                ], 200);
            } else {
                $this->response([
                    'status' => false,
                    'error' => true,
                    'message' => 'ERROR',
                    'system_code' => $this->code03,
                ], 200);
            }
        }
    }

    public function delete_post()
    {
        $id_champion = $this->post('id_champion');

        if ($id_champion != '') {
            $status_borrado = $this->Champions_model->delete_champion($id_champion);
            if($status_borrado){
                $this->response([
                    'status' => true,
                    'error' => false,
                    'message' => 'OK',
                    'system_code' => $this->code01,
                ], 200);
            }else{
                $this->response([
                    'status' => false,
                    'error' => true,
                    'message' => 'ERROR',
                    'system_code' => $this->code02,
                ], 200);
            }
        } else {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'ERROR: '.$this->code03,
                'system_code' => $this->code03,
            ], 200);
        }
    }

    public function update_post()
    {
        $id_champ = $this->post('id_champ');
        $name = $this->post('name');
        $champ_key = $this->post('champ_key');
        $title = $this->post('title');
        $description = $this->post('description');

        if ($name == '' || $champ_key == '' || $title == '' || $description == '' || $id_champ == '') {
            $this->response([
                'status' => false,
                'error' => true,
                'message' => 'Faltan Argumentos.',
            ], 400);
        } else {

            $champion = $this->Champions_model->get_champion($id_champ);

            if (isset($champion['id'])) {
                $params = array(
                    'name' => $name,
                    'champ_key' => $champ_key,
                    'title' => $title,
                    'description' => $description,
                );
    
                if ($this->Champions_model->update_champion($params,$id_champ)) {

                    $championNew = $this->Champions_model->get_champion($id_champ);

                    $this->response([
                        'status' => true,
                        'error' => false,
                        'message' => "OK",
                        'system_code' => $this->code01,
                        'data' => $championNew,
                    ], 200);
                } else {
                    $this->response([
                        'status' => false,
                        'error' => true,
                        'message' => 'ERROR',
                        'system_code' => $this->code04,
                    ], 200);
                }
            }else{
                $this->response([
                    'status' => false,
                    'error' => true,
                    'message' => 'ERROR',
                    'system_code' => $this->code03,
                ], 200);
            }
        }
    }
}
